library(igraph)
source('indicator.R')
g = read.graph("network_hash.txt", directed=F)
g2 = simplify(g)
cluster = fastgreedy.community(g2)
category = read.table("category_hash.txt")
ct = table(cluster$membership,category$V1)
purity(ct)
f_measure(ct)
